import Link from "next/link";
import { ArrowRight, CalendarCheck2, Layers3, Radar, ScanLine, Sparkles } from "lucide-react";

export default function Home() {
  return <div className="page-wrap landing-page">
    <div className="eyebrow"><span className="eyebrow-dot" /> THE CAMPUS EVENT NETWORK</div>
    <section className="landing-hero"><div className="landing-copy"><h1>Everything happening at IITH.<br /><em>Without the noise.</em></h1><p>One intelligent event layer for discovery, planning, and conflict-aware coordination across campus.</p><div className="hero-actions"><Link href="/demo" className="button button-primary">Try guided demo <ArrowRight size={18} /></Link><Link href="/discover" className="button button-secondary">Explore events <ArrowRight size={18} /></Link></div><div className="hero-proof"><span>Built for campus life</span><span>•</span><span>Powered by transparent intelligence</span></div></div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-visual-label"><span className="visual-icon"><Sparkles size={25} /></span><span>Campus signals,<br /><strong>finally connected.</strong></span></div><div className="floating-card float-one"><span className="float-dot cyan-dot" /><div><strong>AI Workshop</strong><small>Sample event · LH3</small></div><span>DEMO</span></div><div className="floating-card float-two"><span className="float-dot amber-dot" /><div><strong>Sample insight</strong><small>Audience overlap example</small></div><Radar size={19} /></div></div></section>
    <div className="section-heading"><div><span className="mini-label">THE EVENTMESH DIFFERENCE</span><h2>More than an event calendar.</h2></div><p>From scattered announcements to one coordinated campus experience.</p></div>
    <section className="feature-grid"><div className="feature-card"><div className="feature-icon"><ScanLine size={22} /></div><h3>Turn posters into events</h3><p>Upload an event poster, review the extracted details, and publish with confidence.</p><span>01 / INGEST</span></div><div className="feature-card"><div className="feature-icon"><Radar size={22} /></div><h3>See conflicts before they happen</h3><p>Spot venue collisions and audience overlap with explainable scores and better slot suggestions.</p><span>02 / COORDINATE</span></div><div className="feature-card"><div className="feature-icon"><Layers3 size={22} /></div><h3>Discover your campus</h3><p>Find relevant events, save the ones you love, and see your evening in one clear timeline.</p><span>03 / PARTICIPATE</span></div></section>
    <section className="landing-cta"><div><CalendarCheck2 size={28} /><h2>Make the most of what’s happening.</h2><p>Your next great campus moment is one click away.</p></div><Link href="/discover" className="button button-primary">Enter EventMesh <ArrowRight size={18} /></Link></section>
  </div>;
}
